### ISSUE TITLE
关于继承提问

### ISSUE THREAD

**Issue by luzexi** [dreamanlan/Cs2Lua#1]
```
1、不完全支持类的继承与泛型（可以实现接口），主要原因是lua的元表机制很难完美实现c#对象继承的详细语义同时还保持良好的效率与可理解性。并且支持接口与partial类后，继承的很多特性可以很优雅的实现。
```
README里这条说明看不懂，意思是不支持继承吗，还是不支持泛型。继承的话，有哪些地方会有问题？
我对继承做了测试，提示说class/struce cant inherit。但虚函数，重载函数，子类调用父类方法，都是对的。既然你说了不完全支持，请明确提示哪里会有问题。

**Comment by dreamanlan** [comment]
实际实现只简单支持了继承，就是大多数lua书上提到的继承模拟。但这种继承与C#的继承语义不是完全等价的。比如子类override了父类的虚函数，如果子类通过”base.父类方法“调用父类方法实现，为了能调到父类的方法实现，现在是使用父类子对象作this去调用的，这样会导致父类方法里调用的其它虚函数不是被子类override的版本而是父类的相应实现，也就是虚函数的语义失效了。
（这个问题的原因我感觉是因为lua用于模拟面向对象的核心机制”元表“是属于对象的，而不是像OO语言那样虚函数表是属于类的。这似乎与javascript的对象机制更接近一些。）

**Comment by dreamanlan** [comment]
泛型的实现最近有一个比较大的修改，目前对泛型的支持比继承可能更接近C#的语义一些（实际上是采用了类似c++模板实例化的方式，对每一个generic实例单独生成一份代码了）
