### ISSUE TITLE
对Xlua的支持是否完整

### ISSUE THREAD

**Issue by wpyzpxw** [dreamanlan/Cs2Lua#2]
dear dreamanlan，
现在对xlua的转换是否完整呢？测试了下Test中的例子，改成xlua，出现一个问题WrapEnumerator是个空的。

**Comment by dreamanlan** [comment]
目前主要是在slua下测试的，xlua的支持需要对utility_xlua.lua进行修改。corountine的实现在slua下是修改了slua代码实现的，xlua下可能也需要类似的机制。

**Comment by Githubxplabs** [comment]
看项目源码 有对xlua的转换检测，是否会加大力度对xlua全力支持？

**Comment by dreamanlan** [comment]
我没有用过xlua，这里包括的utility_xlua.lua只是对xlua支持的一部分，需要对xlua进行的修改或c#扩充没有包括在这里
